bgd-point/point-app-test

- app/Console/Commands/ClearTransaction.php
- app/Console/Commands/EmailApproval.php
- app/Console/Commands/ResetDatabase.php
- app/Console/Commands/SeedDummy.php
- app/Console/Kernel.php
add console #2 
- clear transaction
- email approval
> fix some console

- database/seeds/InjectCutOffBnsSeeder.php
- database/seeds/RejournalCutoffSeeder.php
- packages/point/point-framework/src/Models/Journal.php
Procedur 
1. Run seeder InjectCutOffBnsSeeder
2. cancel form
bank in = 269 BANK-IN/0004/I/17	
locking => 267 PS/COLLECT/0001/I/17
locking => 264 COR/0001/XII/16
bank in = 271 BANK-IN/0005/I/17
locking = 270 PS/COLLECT/0002/I/17
locking = 264 COR/0001/XII/16
bank in = 275 BANK-IN/0006/I/17
locking = 272 PS/COLLECT/0003/I/17
locking = 264 COR/0001/XII/16
bank in = 346 BANK-IN/0005/II/17
locking = 345 PS/COLLECT/0003/II/17
locking = 264 COR/0001/XII/16
> inject data cutoff bns

- app/Console/Commands/RemoveSpace.php
- app/Console/Kernel.php
command 
php artisan dev:trim {table_name} {field_name}
ex: php artisan dev:trim coa coa_number
> add console remove whitespace in field of table

- packages/point/point-finance/src/Http/Controllers/ReportController.php
- packages/point/point-framework/src/Helpers/AccountingHelper.php
- packages/point/point-framework/src/Http/Controllers/Accounting/GeneralLedgerController.php
- packages/point/point-framework/src/Http/Controllers/Accounting/SubLedgerController.php
- packages/point/point-framework/src/views/app/accounting/sub-ledger/index.blade.php
- fix cash bank report
- fix filter accounting->subldger
> Fix revision accounting

- database/seeds/InjectFinanceReferenceManukanSeeder.php
- packages/point/point-finance/src/Http/Controllers/PaymentOrder/PaymentOrderApprovalController.php
run : 
php artisan db:seed --class=InjectFinanceReferenceManukanSeeder
> Fix bug finance payment reference

- packages/point/point-finance/src/Http/Controllers/PaymentOrder/PaymentOrderController.php
- packages/point/point-framework/src/Models/Master/Coa.php
get nonsubledger and not in setting journal
> add function coa filter

- packages/point/point-framework/src/Models/Master/Person.php
count(): Parameter must be an array or an object that implements Countable
> fixed error person.php searchByType tidak perlu where name

- packages/point/point-core/src/assets/themes/appui-backend/js/app.js
- public/core/themes/appui-backend/js/app.js
forgot comma in datepicker selector which makes datepicker that is not date-from and date-to doesn't auto close the datepicker
> [BUGFIX] Datepicker doesn't autoclose

- packages/point/point-purchasing/src/Http/Controllers/Service/PaymentOrderController.php
- packages/point/point-purchasing/src/Http/Routes/purchasing-service.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/payment-order/_menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/payment-order/report.blade.php
added button report
added route to purchase/service/payment-order/report with service/PaymentOrderController@report
added report.blade.php all copied from inventory/payment-order/report
> Feature Purchasing/Service/Payment Order/Report

- packages/point/point-purchasing/src/Http/Controllers/Inventory/PaymentOrderController.php
- packages/point/point-purchasing/src/Http/Routes/purchasing-inventory.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/payment-order/_menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/payment-order/report.blade.php
Sudah bisa sort & filter. Default nya sort by form_date asc, status open.
Sort & filter nya semua di handle di controller, jadi nggak pakai buat function baru di model/helper.
Baru selesai di halaman goods purchase - payment order saja, belum halaman lain.
Apakah sudah benar?
Biar nanti tinggal coppas saja ke halaman lain.
> Feature purchasing/inventory/payment order/report

- packages/point/point-sales/src/views/app/sales/point/service/menu.blade.php
> [BUGFIX] Report header showing when User doesn't have permission to see report

- packages/point/point-sales/src/views/app/sales/point/sales/delivery-order/create-step-2.blade.php
#119 Fixed DeliveryOrderController #non numeric by adding check discount send 0 instead of null
> [BUGFIX] fixed issue #119 

- packages/point/point-sales/src/views/app/sales/point/service/downpayment/show.blade.php
> [BUGFIX] button doesn't appear because wrong permission slug

- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceApprovalController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-purchasing/src/Http/Routes/purchasing-service.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/downpayment/create.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/_menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/create.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/request-approval.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-invoice.blade.php
Button REQUEST APPROVAL di _menu.blade.php
Invoice->Create REQUEST APPROVAL TO
Form APPROVAL ACTION
Halaman request-approval
Email
> [Feature] Purchase service invoice approval

- packages/point/point-purchasing/src/views/app/purchasing/point/service/downpayment/show.blade.php
> [BUGFIX] Fixed wrong permission slug in purchase service downpayment show action

- app/Http/Controllers/DashboardController.php
- packages/point/point-purchasing/src/Models/Service/Invoice.php
- packages/point/point-purchasing/src/Vesa/Service/ServiceInvoiceVesa.php
> VESA Invoice Done

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/purchase-requisition.blade.php
> fix total not working, fix alignment of price and total column

- packages/point/point-framework/src/Http/Controllers/Inventory/InventoryValueReportController.php
- packages/point/point-framework/src/helpers.php
- packages/point/point-framework/src/views/app/inventory/value-report/index.blade.php
> [DONE][Feature] Inventory Report Export

- database/migrations/2018_07_03_170029_create_table_email_history.php
- packages/point/point-framework/src/Models/EmailHistory.php
- packages/point/point-framework/src/Models/Formulir.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/InvoiceController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PaymentOrderController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PurchaseOrderController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PurchaseRequisitionController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/invoice/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/payment-order/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/purchase-order/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/purchase-requisition/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/show.blade.php
php artisan migrate
email history kirim ke supplier saja
halaman selesai :
- Goods Purchase
- Purchase requisition
- Purchase order
- Purchase invoice
- Purchase payment order
- Service Purchase
- Purchase invoice
> [Feature] Email history

- packages/point/point-framework/src/Http/Controllers/Inventory/InventoryValueReportController.php
yang perlu di recalculate stock nama itemnya akan berwarna merah, bold, underline.
tidak bisa screenshot karena tidak punya datanya.
> [MINOR-FIX] Added recalculate_stock check in export excel

- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-sales/src/Http/Controllers/Sales/InvoiceController.php
- packages/point/point-sales/src/Http/Controllers/Sales/PaymentCollectionController.php
- packages/point/point-sales/src/Http/Controllers/Sales/SalesOrderController.php
- packages/point/point-sales/src/Http/Controllers/Sales/SalesQuotationController.php
- packages/point/point-sales/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-sales/src/Http/Controllers/Service/PaymentCollectionController.php
- packages/point/point-sales/src/views/app/sales/point/sales/invoice/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/sales-order/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/sales-quotation/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/service/invoice/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/service/payment-collection/show.blade.php
done page :
- Goods Sales
- Quotation
- Order
- Invoice
- Payment Collection
- Service Sales
- Invoice
- Payment Collection
> [FEATURE] email history sales

- packages/point/point-purchasing/src/Http/Controllers/Inventory/InvoiceController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PaymentOrderController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PurchaseOrderController.php
- packages/point/point-purchasing/src/Http/Controllers/Inventory/PurchaseRequisitionController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/PaymentOrderController.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/payment-order/show.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/external/service-payment-order-pdf.blade.php
fix send email error in purchase service payment order (wrong variable)
added email history in purchase service payment order
optimize eloquent
> Email History for Purchase Service Payment Order, and fix send email error

- packages/point/point-expedition/src/views/app/expedition/point/payment-order/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/payment-order/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/retur/create-step-1.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/retur/create-step-2.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/retur/edit.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/retur/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/retur/create-step-1.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/retur/create-step-2.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/retur/edit.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/retur/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/payment-order/index.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/index.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/retur/create-step-1.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/retur/create-step-2.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/retur/edit.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/retur/index.blade.php
- packages/point/point-sales/src/views/app/sales/point/service/payment-collection/index.blade.php
changed date-date-value from date_format_get to date_format_masking
> [BUGFIX] Datepicker broken in some pages

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-invoice.blade.php
> [FEATURE] Add detail in email approval purchase service invoice

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-payment-order.blade.php
Email apporoval purchasing service payment order added extra row if invoice has previous payment order
> Email Purchasing Service Payment Order

- packages/point/point-sales/src/views/app/sales/point/service/report.blade.php
https://trello.com/c/z5dBVEXQ/19-tampilkan-total-qty-dan-amount-per-tanggal-di-halaman-sales-report
> Sales service report added subtotal per invoice

- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/payment-order/index.blade.php
https://trello.com/c/MVmSKM67/39-tampilakn-nominal-di-list-data-purchase-service-dan-payment-order-service
> Tambah nominal purchasing service list data

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/purchase-order.blade.php
https://trello.com/c/LvP03k7o/37-request-approval-purchase-order-beda-subtotal-dan-total
Changed :
- Added tax detail
- Changed some alignment
- Removed unused css
- Changed form number to clickable link
> [FIX] Purchasing inventory purchase order email approval

- app/Http/Controllers/DashboardController.php
- packages/point/point-finance/src/Vesa/PaymentVesa.php
- resources/views/app/index.blade.php
> Dashboard show approved payment, ready to cash out

- resources/views/app/index.blade.php
Fixed error undefined variable array_vesa_payment.
Baru tau ternyata app.index ini dipanggil di banyak controller, dan di controller lain nggak ada variabel array_vesa_payment. Makanya error undefined variable.
Sudah beres, tinggal kasih if isset
> Added list of approved payment order in dashboard

- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/create.blade.php
> [Minor-fix] Purchasing service invoice create fixed add service row not selectized

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-payment-order.blade.php
> Purchasing service payment order email approval

- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceApprovalController.php
Error dari bu Mirna
wrong function called when requesting approval purchase service invoice
> Fixed error when requesting approval purchase service invoice

- packages/point/point-framework/src/views/app/include/_approval_status_label.blade.php
> added time approved in approved label

- packages/point/point-framework/src/views/app/include/_approval_status_label.blade.php
added check if $approval_at exist
> Fixed error undefined variable because apparently not all pages send $approval_at to approval_status_label

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-payment-order.blade.php
added class allow-wrap to invoice number column
https://trello.com/c/ceiKFGpn/44-kecilkan-kolom-invoice-number-di-email-approval-purchase-service-payment-order
> Purchasing service payment order email approval 

- database/seeds/FrameworkPermissionTableSeeder.php
- database/seeds/TemporaryInsertSeeder.php
- packages/point/point-framework/src/Http/Controllers/Master/ItemController.php
- packages/point/point-framework/src/Models/Master/Item.php
- packages/point/point-framework/src/database/seeds/FrameworkPermissionTableSeeder.php
- packages/point/point-framework/src/views/app/master/item/index.blade.php
Run `php artisan db:seed --class=TemporaryInsertSeeder`
> Master Item show cogs and pricing

- app/Console/Commands/EmailApproval.php
- packages/point/point-accounting/src/Http/Controllers/Cutoff/CutOffAccountApprovalController.php
- packages/point/point-accounting/src/Http/Controllers/Cutoff/CutOffFixedAssetsApprovalController.php
- packages/point/point-accounting/src/Http/Controllers/Cutoff/CutOffInventoryApprovalController.php
- packages/point/point-accounting/src/Http/Controllers/Cutoff/CutOffPayableApprovalController.php
- packages/point/point-accounting/src/Http/Controllers/Cutoff/CutOffReceivableApprovalController.php
- packages/point/point-accounting/src/Http/Controllers/MemoJournalApprovalController.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-fixed-assets.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-inventory.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-payable.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-receivable.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/memo-journal.blade.php
- packages/point/point-manufacture/src/Http/Controllers/FormulaApprovalController.php
- packages/point/point-manufacture/src/Http/Controllers/InputApprovalController.php
- packages/point/point-manufacture/src/views/emails/manufacture/point/approval/formula.blade.php
- packages/point/point-manufacture/src/views/emails/manufacture/point/approval/input.blade.php
selesai menu manufacture & accounting
> done auto resend email approval for all feature

- packages/point/point-framework/src/Helpers/JournalHelper.php
removed 2 lines in journal helper
> fixed opening and ending in trial balance not 0

- packages/point/point-framework/src/Http/Controllers/Inventory/InventoryValueReportController.php
- packages/point/point-framework/src/views/app/inventory/value-report/index.blade.php
added column unit and dropdown to filter account
> inventory value report

- packages/point/point-framework/src/Http/Controllers/Accounting/TrialBalanceController.php
- packages/point/point-framework/src/views/app/accounting/trial-balance/_data.blade.php
> trial balance including deleted coa in export excel, added rounding in export excel to 2 precision

- packages/point/point-finance/src/Models/PaymentReference.php
- packages/point/point-finance/src/Vesa/PaymentVesa.php
added where formulir is not cancelled in paymentvesa controller
> fixed bug cancelled purchase inventory downpayment still appear in vesa dashboard

- packages/point/point-finance/src/Http/Controllers/Cash/CashOutController.php
- packages/point/point-finance/src/Http/Controllers/PaymentController.php
- packages/point/point-finance/src/Http/Routes/payment.php
- packages/point/point-finance/src/views/app/finance/point/bank/in/show.blade.php
- packages/point/point-finance/src/views/app/finance/point/bank/out/show.blade.php
- packages/point/point-finance/src/views/app/finance/point/cash/in/show.blade.php
- packages/point/point-finance/src/views/app/finance/point/cash/out/show.blade.php
- packages/point/point-framework/src/views/email/cancel-formulir.blade.php
user with delete permission still see cancel form button
users available in select to ask approval are only user with delete permission
> added request cancel cash in/out & bank in/out for user without delete permission

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/downpayment.blade.php
> fixed error email approval goods purchase downpayment

- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-payment-order.blade.php
> Add payment order others detail in email approval

- app/Console/Commands/EmailApproval.php
link dari email kurang /, jadi nyambung kbretail.app.point.redpurchasing
tapi saya nggak bisa test nya, dan kalau dijalankan di localhost sih bener
> fixed error domain link

- packages/point/point-framework/src/Vesa/MasterVesa.php
> removed but from vesa stock reminder

- packages/point/point-framework/src/Vesa/MasterVesa.php
> Vesa wrong value stock reminder

- app/Console/Commands/EmailApproval.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-fixed-assets.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-inventory.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-payable.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off-receivable.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/cut-off.blade.php
- packages/point/point-accounting/src/views/emails/accounting/point/approval/memo-journal.blade.php
- packages/point/point-expedition/src/views/emails/expedition/point/approval/downpayment.blade.php
- packages/point/point-expedition/src/views/emails/expedition/point/approval/expedition-order.blade.php
- packages/point/point-finance/src/views/emails/finance/point/approval/cash-advance.blade.php
- packages/point/point-finance/src/views/emails/finance/point/approval/payment-order.blade.php
- packages/point/point-inventory/src/views/emails/inventory/point/approval/inventory-usage-email.blade.php
- packages/point/point-inventory/src/views/emails/inventory/point/approval/stock-correction.blade.php
- packages/point/point-inventory/src/views/emails/inventory/point/approval/transfer-item-email.blade.php
- packages/point/point-manufacture/src/views/emails/manufacture/point/approval/formula.blade.php
- packages/point/point-manufacture/src/views/emails/manufacture/point/approval/input.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/payment-order.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/purchase-order.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/purchase-requisition.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-downpayment.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-invoice.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-payment-order.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/delivery-order.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/downpayment.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/payment-collection.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/sales-quotation.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/service-downpayment.blade.php
- packages/point/point-sales/src/views/app/emails/sales/point/approval/service-payment-collection.blade.php
got extra slash if email is resent by vesa
> fixed email approval button not working

- packages/point/point-framework/src/Models/Formulir.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-invoice.blade.php
> added reason edit in email approval, added eloquent relations to get previous update of formulir

- database/seeds/FixWrongClosedPurchaseServiceInvoice.php
- packages/point/point-finance/src/views/app/finance/point/debts-aging-report/_detail.blade.php
Request dari ce Vera
minta supaya nomornya urut
> Minor fix/debts aging index number

- packages/point/point-framework/src/Http/Controllers/Accounting/GeneralLedgerController.php
- packages/point/point-framework/src/views/app/accounting/general-ledger/_data-export.blade.php
Request dari ce Maya
https://trello.com/c/jHZqkdHO/64-general-ledger-export-excel-sekarang-tidak-muncul-nama-account-di-baris-1-dulu-katanya-muncul
https://github.com/bgd-point/point-app-test/commit/7f36bbc085eeeee201a09c6baae046fe8b824bbe#r30859097
> add coa name in export general ledger

- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/edit.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/show.blade.php
> Sales payment collection payment type

- app/Http/Controllers/DashboardController.php
- app/Http/routes.php
- packages/point/point-expedition/src/views/app/expedition/point/invoice/basic/show.blade.php
- packages/point/point-expedition/src/views/app/expedition/point/invoice/show.blade.php
- packages/point/point-framework/src/Http/Controllers/Accounting/GeneralLedgerController.php
- packages/point/point-framework/src/views/app/accounting/general-ledger/_data-export.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/fixed-assets/invoice/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/inventory/invoice/show.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/invoice/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/edit.blade.php
- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/show.blade.php
- packages/point/point-sales/src/views/app/sales/point/service/invoice/show.blade.php
- resources/views/app/index.blade.php
more or less....
button location : dashboard
doing ajax get request to /sync-budget
curl is still not set properly
> button sync-budget in dashboard

- database/migrations/2018_11_01_025854_add_column_cash_outed.php
- database/seeds/UpdateCashAdvanceHandedOverForExistingData.php
- packages/point/point-finance/src/Http/Controllers/CashAdvanceController.php
- packages/point/point-finance/src/Http/Controllers/ReportController.php
- packages/point/point-finance/src/Http/Routes/payment.php
- packages/point/point-finance/src/Models/CashAdvance.php
- packages/point/point-finance/src/views/app/finance/point/cash-advance/_menu.blade.php
- packages/point/point-finance/src/views/app/finance/point/cash-advance/index.blade.php
- packages/point/point-finance/src/views/app/finance/point/cash-advance/show.blade.php
Run command: 
```
php artisan migrate
php artisan db:seed --class=UpdateCashAdvanceHandedOverForExistingData
```
> cash advance

- database/seeds/FixCloseFullyPaidInvoice.php
php artisan db:seed --class=FixCloseFullyPaidInvoice
> added seeder to close invoice that has remaining 0

- packages/point/point-sales/src/views/app/sales/point/sales/payment-collection/show.blade.php
> sales indirect payment collection show doesn't have authorized user (creator and approver)

- database/migrations/2018_11_15_165210_create_point_purchasing_service_purchase_order_table.php
- database/migrations/2018_11_15_165851_create_point_purchasing_service_purchase_order_detail_table.php
- database/seeds/PointPurchasingPermissionSeeder.php
- database/seeds/PointPurchasingServicePurchaseOrderPermission.php
- database/seeds/PointPurchasingServicePurchaseOrderQuickSeeder.php
- packages/point/point-purchasing/src/Helpers/ServiceInvoiceHelper.php
- packages/point/point-purchasing/src/Helpers/ServicePurchaseOrderHelper.php
- packages/point/point-purchasing/src/Http/Controllers/Service/InvoiceController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/PurchaseOrderApprovalController.php
- packages/point/point-purchasing/src/Http/Controllers/Service/PurchaseOrderController.php
- packages/point/point-purchasing/src/Http/Requests/ServiceInvoiceRequest.php
- packages/point/point-purchasing/src/Http/Requests/ServicePurchaseOrderRequest.php
- packages/point/point-purchasing/src/Http/Routes/purchasing-service.php
- packages/point/point-purchasing/src/Models/Service/PurchaseOrder.php
- packages/point/point-purchasing/src/Models/Service/PurchaseOrderDetail.php
- packages/point/point-purchasing/src/database/seeds/PointPurchasingFormulirNumberSeeder.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/_menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/create-step-1.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/invoice/create-step-2.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/_menu.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/archived.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/create.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/edit.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/index.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/request-approval.blade.php
- packages/point/point-purchasing/src/views/app/purchasing/point/service/purchase-order/show.blade.php
- packages/point/point-purchasing/src/views/emails/purchasing/point/approval/service-purchase-order.blade.php
https://trello.com/c/9DtSokSB/81-purchasing-service-purchase-order
run:
`php artisan db:seed --class=PointPurchasingServicePurchaseOrderQuickSeeder`
`php artisan migrate`
> [DONE] Purchasing service purchase order
